import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const securityApi = createApi({
  reducerPath: "securityApi",
  baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:8080" }),
  prepareHeaders: (headers, { getState }) => {
    const token = localStorage.getItem("jwtToken");
    console.log("Token->", token);
    if (token) {
      headers.set("Authorization", "Bearer ${token}");
      return headers;
    }
  },
  /**
   * endpoints are a set of operations that you want to perhtmlForm against your server.
   * They're defined as an object using the builder synax.
   * I have created a query endpoint that makes a GET request to the contacts route,
   * then i exported the React hook generated by this endpoint
   */
  endpoints: (builder) => ({
    getContactDetails: builder.query({
      query: () => ({}),
    }),
  }),
});

// Export hooks htmlFor usage in functional components, which are
// auto-generated based on the defined endpoints
export const { useGetContactDetailsQuery } = securityApi;
